#!/usr/bin/env bash
# =============================================================================
# lang_en.sh — English messages for setup.sh (loaded via UI_LANG=en).
# Defines every M_* variable ; contains no logic.
# =============================================================================

# Shared tags/prompts (scripts/lib.sh)
INFO_TAG="[INFO]"; OK_TAG="[OK]"; WARN_TAG="[WARNING]"; ERROR_TAG="[ERROR]"
ASK_YES_NO_PROMPT_Y="[Y/n]"; ASK_YES_NO_PROMPT_N="[y/N]"; ASK_CHOICE_WORD="Choice"

# --- Banner and mode selection ---
M_TAGLINE="Forge / Fabric / Vanilla / Modpacks — Always Free (ARM)"
M_WELCOME_Q="Welcome! How would you like to proceed?"
M_OPT_GUIDE="Guided mode — I walk you through every step (recommended)"
M_OPT_EXPERT="Expert mode — I know what I'm doing, straight to the point"
M_LETS_GO="Let's go! We'll do this together, no stress 😊"

# --- Wizard: Oracle account ---
M_W1_TITLE="STEP 1/3 — Your Oracle account (you only do this ONCE)"
M_W1_HAVE="Do you already have an Oracle Cloud account?"
M_W1_SKIP="Perfect, let's jump straight to the next part!"
M_W1_L1="Oracle will LEND you a computer in the cloud, free, forever."
M_W1_L2="(That's their way of attracting customers — and you get to benefit.)"
M_W1_L3="For that, you need an account. Here is how:"
M_W1_S1="1. Go to https://cloud.oracle.com → « Start for free » button"
M_W1_S2="2. Enter an email + password  (write them down somewhere!)"
M_W1_S3="3. Name, country, phone number (to check you are a real person)"
M_W1_S4="4. A bank card will be asked for: it is JUST an identity check."
M_W1_S4b="   Nothing is ever charged as long as you stay on the free tier."
M_W1_S4c="   Ask an adult for permission if needed 😉"
M_W1_S5="5. Home Region: pick UK South (London) or Germany Central"
M_W1_S5b="   (Frankfurt) — the closest one means the least lag."
M_W1_S5c="   ⚠ This choice is permanent, and the confirmation email can"
M_W1_S5d="   take up to 30 minutes to arrive."
M_W1_OPENQ="Want me to open the sign-up page in your browser?"
M_W1_OPENFAIL="Could not open the browser — go to https://cloud.oracle.com"
M_W1_WARN="If Oracle offers « Upgrade to Pay As You Go »: DECLINE. Stay on free."
M_W1_WAITTIP="the confirmation email can take 30 minutes, go grab a glass of water 🥤"

# --- Wizard: VM creation ---
M_W2_TITLE="STEP 2/3 — Create the machine (the « VM ») for your server"
M_W2_HAVE="Is your machine already created (with its IP address)?"
M_W2_SKIP="Great, let's move on to the configuration!"
M_W2_L1="On cloud.oracle.com: ☰ menu (top left) → Compute → Instances"
M_W2_L2="→ big blue « Create instance » button. Fill in EXACTLY this:"
M_W2_S1="• Name          : anything you like (e.g. minecraft)"
M_W2_S2="• Image [Edit]  : Ubuntu 22.04 or 24.04   (NOT « Minimal »)"
M_W2_S3="• Shape [Edit]  : Ampere tab → VM.Standard.A1.Flex"
M_W2_S3b="                 → OCPUs : 2    Memory : 12 GB"
M_W2_S4="• SSH keys  ⚠ THE MOST IMPORTANT STEP ⚠"
M_W2_S4b="    1. « Generate a key pair »"
M_W2_S4c="    2. « Save Private Key » → keep this file VERY safe:"
M_W2_S4d="       it is the key to your machine. Lost key = lost machine!"
M_W2_S4e="    3. « Save Public Key »"
M_W2_S5="• « Create » button, then wait 2 to 5 minutes..."
M_W2_OPENQ="Open the Oracle console in your browser?"
M_W2_OPENFAIL="Could not open the browser — go to https://cloud.oracle.com"
M_W2_WAITTIP="wait for the green « Running » status on the instance page"
M_W2_DONE1="Carefully note the « Public IP Address » shown (e.g. 129.213.56.123):"
M_W2_DONE2="we will ask you for it in the next step."

# --- Patient waiting ---
M_WAIT_REASSURE="No worries, take your time — the program is happily waiting here."
M_WAIT_TIPPREFIX="Tip: "
M_WAIT_Q="All done?"

# --- Configuration questions ---
M_STEP3_TITLE="STEP 3/3 — Your server settings"
M_IP_HINT1="The IP is the « postal address » of your machine: Oracle console →"
M_IP_HINT2="Compute → Instances → « Public IP Address » column."
M_IP_HINT3="It looks like: 129.213.56.123"
M_IP_PROMPT="→ Public IP of your Oracle VM: "
M_IP_OK="Valid IP:"
M_IP_BAD="That is not a valid IP address. Example: 129.213.56.123"
M_IP_WHERE="(copy-paste the « Public IP Address » value from the Oracle console)"
M_KEY_INTRO_G1="Now, your KEY: the « Save Private Key » file you downloaded when"
M_KEY_INTRO_G2="you created the machine. It is the key to your house 🔑 — we will use it"
M_KEY_INTRO_G3="to open the door of your server. It is often in your Downloads folder."
M_KEY_INTRO_E1="SSH private key downloaded from the Oracle console"
M_KEY_INTRO_E2="(a file like ssh-key-2026-XX-XX.key or *.pem, often in Downloads)."
M_KEY_PROMPT="→ Path to your SSH private key: "
M_KEY_FOUNDQ="Key found:"
M_KEY_USEQ="— use it?"
M_KEY_NOTFOUND="File not found:"
M_KEY_PERMWARN="Could not adjust key permissions (ignored on Windows)."
M_KEY_OK="SSH key:"
M_HINT_ENTER1="💡 Tip: for every question, just press ENTER to keep the"
M_HINT_ENTER2="   recommended answer — that's the easiest way!"
M_TYPE_Q="What kind of Minecraft server?"
M_TYPE_OPT1="Vanilla (pure, no mods)"
M_TYPE_OPT2="Forge (classic mods — recommended for 1.20.1)"
M_TYPE_OPT3="Fabric (modern mods, lightweight)"
M_TYPE_OPT4="Preset modpack (CurseForge server pack)"
M_VER_PROMPT="Minecraft version [1.20.1]: "
M_VER_BAD="Invalid version (expected formats: 1.20.1, 1.21...)"
M_VER_OK="Minecraft version:"
M_RAM_LABEL="Server RAM in GB (max 8 on Always Free)"
M_RAM_OK="JVM RAM allocated:"
M_PLAYERS_LABEL="Maximum number of players"
M_CRAFTY_Q="Install Crafty Controller (web admin panel)?"
M_CRAFTY_INFO1="Panel available after installation at https://<IP>:8443"
M_CRAFTY_INFO2="Management via SSH and the utils/ scripts only."
M_MOD_TITLE="Available modpacks:"
M_MOD_PROMPT="→ Modpack identifier: "
M_MOD_BAD="Unknown modpack:"
M_URL_INFO1="Last thing: the download address of the « Server Pack »."
M_URL_INFO2="On the modpack's CurseForge page: Files tab → pick a"
M_URL_INFO3b_placeholder=""
M_URL_INFO3="version → Additional Files → right-click the « Server Pack » file →"
M_URL_INFO4="« Copy link address »."
M_URL_EXAMPLE="Example URL: https://mediafilez.forgecdn.net/files/1234/567/pack.zip"
M_URL_PROMPT="→ Server pack URL (.zip): "
M_URL_BAD="Invalid URL (direct http(s) URL, no spaces or special characters)."

# --- Summary and confirmation ---
M_SUM_TITLE="                  CONFIGURATION SUMMARY"
M_SUM_IP="Oracle IP"
M_SUM_TYPE="Server type"
M_SUM_MOD="Modpack"
M_SUM_VER="MC version"
M_SUM_RAM="JVM RAM"
M_SUM_PLAYERS="Max players"
M_SUM_CRAFTY="Crafty panel"
M_CONFIRM_Q="Confirm and start the installation?"
M_CANCELLED="Installation cancelled."

# --- Execution ---
M_DRY_WARN="SIMULATION MODE (--dry-run): no remote action will be executed."
M_WOULD_RUN="Commands that would be executed:"
M_SSH_TEST="Testing SSH connection to"
M_SSH_OK="Connection successful — the door opens with your key 🔓"
M_SSH_FAIL_L1="Could not open the door to your machine 😕 Check in this order:"
M_SSH_FAIL_1="  1. The IP: is it really the « Public IP Address » on your instance page?"
M_SSH_FAIL_2="  2. The key: is it really the « Save Private Key » file from creation?"
M_SSH_FAIL_2b="     (not the « Public Key », and not some other file)"
M_SSH_FAIL_3="  3. Is the machine « Running » (green dot) in the Oracle console?"
M_SSH_FAIL_HELP="Detailed help: docs/en/troubleshooting.md (see « Permission denied »)"
M_TRANSFER_1="Transferring files to the VM"
M_TRANSFER_2="Files transferred."
M_PROV_1="Here we go! Installation takes 5 to 10 minutes and runs on its own:"
M_PROV_2="your server is being born 🐣 (you can go grab a glass of water 🥤)"
M_PROV_3="Running provisioning on the VM ..."
M_PROV_DONE="Packages installed on the remote VM"
M_CONF_SAVED="Local configuration saved to .server.conf"

# --- Final banner ---
M_FINAL_OK="INSTALLATION COMPLETE! 🎉"
M_FINAL_ADDR="📍 YOUR SERVER'S ADDRESS (send it to your friends!):"
M_FINAL_KNOW="AND NOW, 3 things to know:"
M_FINAL_1="1️⃣  YOU MUST OPEN THE PORTS (once, 3 minutes — otherwise nobody"
M_FINAL_1b="     can connect) → docs/en/vcn-setup.md"
M_FINAL_2_MOD="2️⃣  Every player must install the SAME mods on THEIR computer"
M_FINAL_2_MODb="     with the CurseForge app (same modpack, same version)."
M_FINAL_2_VAN="2️⃣  In Minecraft: Multiplayer → Add Server → paste the"
M_FINAL_2_VANb="     address above → Join!"
M_FINAL_3="3️⃣  To become the boss in-game (admin), run:"
M_FINAL_3b="       ./utils/console.sh \"op YourName\""
M_FINAL_TOOLS="Toolbox: ./utils/backup.sh (backup) — ./utils/monitor.sh (monitoring)"
M_FINAL_HELP="Any problem? : docs/en/troubleshooting.md"
M_FINAL_GUIDEQ="Open the « open the ports » guide in your browser now?"
M_FINAL_GUIDEFALL="Read the file docs/en/vcn-setup.md"
M_FINAL_CRAFTYQ="Open the Crafty panel (your server's web interface)?"
M_FINAL_CRAFTYFALL="Panel:"

# --- Errors ---
M_ERR_OS="Unsupported OS:"
M_ERR_OS_HINT="Use Linux, macOS or Git Bash (Windows)."
M_ERR_TOOL="Missing required tool:"
M_ERR_IP="Invalid IP:"
M_ERR_TYPE="Invalid server type:"
M_ERR_VER="Invalid Minecraft version:"
M_ERR_RAM="GB RAM invalid (between 2 and 8 — Always Free 12 GB quota)"
M_ERR_KEY="SSH key not found:"
M_ERR_CRAFTY="--crafty must be true or false"
M_ERR_MOD="Unknown modpack:"
M_ERR_URL="--pack-url required for a modpack (valid direct http(s) URL)"
M_ERR_OPT="Unknown option:"
M_ERR_LANG="--lang expects 'fr' or 'en'"
