#!/usr/bin/env bash
# =============================================================================
# lang_fr.sh — Messages en français pour setup.sh (chargé via UI_LANG=fr).
# Définit toutes les variables M_* ; ne contient aucune logique.
# =============================================================================

# Tags/prompts partagés (scripts/lib.sh)
INFO_TAG="[INFO]"; OK_TAG="[OK]"; WARN_TAG="[ATTENTION]"; ERROR_TAG="[ERREUR]"
ASK_YES_NO_PROMPT_Y="[O/n]"; ASK_YES_NO_PROMPT_N="[o/N]"; ASK_CHOICE_WORD="Choix"

# --- Bannière et choix du mode ---
M_TAGLINE="Forge / Fabric / Vanilla / Modpacks — Always Free (ARM)"
M_WELCOME_Q="Bienvenue ! Comment veux-tu procéder ?"
M_OPT_GUIDE="Mode guide — je t'accompagne étape par étape (recommandé)"
M_OPT_EXPERT="Mode expert — je sais déjà faire, va droit au but"
M_LETS_GO="C'est parti ! On va faire ça ensemble, sans stress 😊"

# --- Assistant : compte Oracle ---
M_W1_TITLE="ÉTAPE 1/3 — Ton compte Oracle (à ne faire qu'UNE seule fois)"
M_W1_HAVE="As-tu déjà un compte Oracle Cloud ?"
M_W1_SKIP="Parfait, on passe directement à la suite !"
M_W1_L1="Oracle va te PRÊTER gratuitement, à vie, un ordinateur dans le cloud."
M_W1_L2="(C'est leur façon d'attirer des clients — et toi, tu en profites.)"
M_W1_L3="Pour ça, il te faut un compte. Voici comment faire :"
M_W1_S1="1. Va sur https://cloud.oracle.com → bouton « Start for free »"
M_W1_S2="2. Donne un email + un mot de passe  (note-les quelque part !)"
M_W1_S3="3. Nom, pays, numéro de téléphone (pour vérifier que tu existes)"
M_W1_S4="4. Une carte bancaire sera demandée : c'est JUSTE une vérification"
M_W1_S4b="   d'identité. Rien n'est prélevé tant que tu restes en gratuit."
M_W1_S4c="   Demande l'autorisation d'un adulte si besoin 😉"
M_W1_S5="5. Région (« Home Region ») : choisis UK South (Londres) ou"
M_W1_S5b="   Germany Central (Francfort) — le plus proche = le moins de lag."
M_W1_S5c="   ⚠ Ce choix est définitif et l'email de confirmation peut"
M_W1_S5d="   mettre 30 minutes à arriver."
M_W1_OPENQ="Veux-tu que j'ouvre la page d'inscription dans ton navigateur ?"
M_W1_OPENFAIL="Impossible d'ouvrir le navigateur — va sur https://cloud.oracle.com"
M_W1_WARN="Si Oracle propose « Upgrade to Pay As You Go » : REFUSE. Reste en gratuit."
M_W1_WAITTIP="l'email de confirmation peut prendre 30 minutes, va boire un verre d'eau 🥤"

# --- Assistant : création de la VM ---
M_W2_TITLE="ÉTAPE 2/3 — Créer la machine (la « VM ») de ton serveur"
M_W2_HAVE="Ta machine est-elle déjà créée (avec son adresse IP) ?"
M_W2_SKIP="Super, on passe à la configuration !"
M_W2_L1="Sur cloud.oracle.com : menu ☰ (en haut à gauche) → Compute → Instances"
M_W2_L2="→ gros bouton bleu « Create instance ». Remplis EXACTEMENT ceci :"
M_W2_S1="• Name          : ce que tu veux (ex. minecraft)"
M_W2_S2="• Image [Edit]  : Ubuntu 22.04 ou 24.04   (PAS « Minimal »)"
M_W2_S3="• Shape [Edit]  : onglet Ampere → VM.Standard.A1.Flex"
M_W2_S3b="                 → OCPUs : 2    Memory : 12 GB"
M_W2_S4="• SSH keys  ⚠ L'ÉTAPE LA PLUS IMPORTANTE ⚠"
M_W2_S4b="    1. « Generate a key pair »"
M_W2_S4c="    2. « Save Private Key » → garde ce fichier PRÉCIEUSEMENT :"
M_W2_S4d="       c'est la clé de ta machine. Perdue = machine perdue !"
M_W2_S4e="    3. « Save Public Key »"
M_W2_S5="• Bouton « Create », puis patiente 2 à 5 minutes..."
M_W2_OPENQ="Ouvrir la console Oracle dans ton navigateur ?"
M_W2_OPENFAIL="Impossible d'ouvrir le navigateur — va sur https://cloud.oracle.com"
M_W2_WAITTIP="attends le statut vert « Running » sur la page de l'instance"
M_W2_DONE1="Note bien le « Public IP Address » affiché (ex. 129.213.56.123) :"
M_W2_DONE2="on va te le demander à l'étape suivante."

# --- Attente patiente ---
M_WAIT_REASSURE="Pas de souci, prends ton temps — le programme attend sagement ici."
M_WAIT_TIPPREFIX="Astuce : "
M_WAIT_Q="C'est fait ?"

# --- Questions de configuration ---
M_STEP3_TITLE="ÉTAPE 3/3 — Les informations de ton serveur"
M_IP_HINT1="L'IP est l'« adresse postale » de ta machine : console Oracle →"
M_IP_HINT2="Compute → Instances → colonne « Public IP Address »."
M_IP_HINT3="Elle ressemble à : 129.213.56.123"
M_IP_PROMPT="→ IP publique de ta VM Oracle : "
M_IP_OK="IP valide :"
M_IP_BAD="Ce n'est pas une adresse IP valide. Exemple : 129.213.56.123"
M_IP_WHERE="(copie-colle la valeur « Public IP Address » de la console Oracle)"
M_KEY_INTRO_G1="Maintenant, ta CLÉ : le fichier « Save Private Key » téléchargé quand tu"
M_KEY_INTRO_G2="as créé la machine. C'est la clé de ta maison 🔑 — on va l'utiliser pour"
M_KEY_INTRO_G3="ouvrir la porte de ton serveur. Elle se trouve souvent dans Téléchargements."
M_KEY_INTRO_E1="Clé SSH privée téléchargée depuis la console Oracle"
M_KEY_INTRO_E2="(fichier du type ssh-key-2026-XX-XX.key ou *.pem, souvent dans Téléchargements)."
M_KEY_PROMPT="→ Chemin de la clé privée SSH : "
M_KEY_FOUNDQ="Clé trouvée :"
M_KEY_USEQ="— l'utiliser ?"
M_KEY_NOTFOUND="Fichier introuvable :"
M_KEY_PERMWARN="Impossible d'ajuster les permissions de la clé (ignoré sous Windows)."
M_KEY_OK="Clé SSH :"
M_HINT_ENTER1="💡 Astuce : pour chaque question, appuie simplement sur ENTRÉE pour"
M_HINT_ENTER2="   garder la réponse conseillée — c'est ce qu'il y a de plus simple !"
M_TYPE_Q="Quel type de serveur Minecraft ?"
M_TYPE_OPT1="Vanilla (pur, sans mods)"
M_TYPE_OPT2="Forge (mods classiques — recommandé pour 1.20.1)"
M_TYPE_OPT3="Fabric (mods modernes, léger)"
M_TYPE_OPT4="Modpack préconfiguré (server pack CurseForge)"
M_VER_PROMPT="Version Minecraft [1.20.1] : "
M_VER_BAD="Version invalide (formats attendus : 1.20.1, 1.21...)"
M_VER_OK="Version Minecraft :"
M_RAM_LABEL="RAM pour le serveur en Go (max 8 sur l'Always Free)"
M_RAM_OK="RAM allouée à la JVM :"
M_PLAYERS_LABEL="Nombre maximum de joueurs"
M_CRAFTY_Q="Installer Crafty Controller (panel web d'administration) ?"
M_CRAFTY_INFO1="Panel accessible après installation sur https://<IP>:8443"
M_CRAFTY_INFO2="Gestion via SSH et les scripts utils/ uniquement."
M_MOD_TITLE="Modpacks disponibles :"
M_MOD_PROMPT="→ Identifiant du modpack : "
M_MOD_BAD="Modpack inconnu :"
M_URL_INFO1="Dernière chose : l'adresse de téléchargement du « Server Pack »."
M_URL_INFO2="Sur la page CurseForge du modpack : onglet Files → choisis une version"
M_URL_INFO3b_placeholder=""
M_URL_INFO3="Additional Files → clic droit sur le fichier « Server Pack » →"
M_URL_INFO4="« Copier l'adresse du lien »."
M_URL_EXAMPLE="Exemple d'URL : https://mediafilez.forgecdn.net/files/1234/567/pack.zip"
M_URL_PROMPT="→ URL du server pack (.zip) : "
M_URL_BAD="URL invalide (URL http(s) directe, sans espaces ni caractères spéciaux)."

# --- Résumé et confirmation ---
M_SUM_TITLE="                 RÉSUMÉ DE CONFIGURATION"
M_SUM_IP="IP Oracle"
M_SUM_TYPE="Type serveur"
M_SUM_MOD="Modpack"
M_SUM_VER="Version MC"
M_SUM_RAM="RAM JVM"
M_SUM_PLAYERS="Joueurs max"
M_SUM_CRAFTY="Panel Crafty"
M_CONFIRM_Q="Confirmer et lancer l'installation ?"
M_CANCELLED="Installation annulée."

# --- Exécution ---
M_DRY_WARN="MODE SIMULATION (--dry-run) : aucune action distante ne sera exécutée."
M_WOULD_RUN="Commandes qui seraient exécutées :"
M_SSH_TEST="Test de connexion SSH vers"
M_SSH_OK="Connexion réussie — la porte s'ouvre avec ta clé 🔓"
M_SSH_FAIL_L1="Impossible d'ouvrir la porte de ta machine 😕 Vérifie dans l'ordre :"
M_SSH_FAIL_1="  1. L'IP : c'est bien celle de « Public IP Address » sur la page de ton instance ?"
M_SSH_FAIL_2="  2. La clé : c'est bien le fichier « Save Private Key » téléchargé à la création ?"
M_SSH_FAIL_2b="     (pas le « Public Key », et pas un autre fichier)"
M_SSH_FAIL_3="  3. La machine est « Running » (point vert) dans la console Oracle ?"
M_SSH_FAIL_HELP="Aide détaillée : docs/troubleshooting.md (section « Permission denied »)"
M_TRANSFER_1="Transfert des fichiers vers la VM"
M_TRANSFER_2="Fichiers transférés."
M_PROV_1="C'est parti ! L'installation dure 5 à 10 minutes et tourne toute seule :"
M_PROV_2="ton serveur est en train de naître 🐣 (tu peux aller boire un verre d'eau 🥤)"
M_PROV_3="Exécution du provisionnement sur la VM ..."
M_PROV_DONE="Packages installés sur la VM distante"
M_CONF_SAVED="Configuration locale sauvegardée dans .server.conf"

# --- Bannière finale ---
M_FINAL_OK="INSTALLATION TERMINÉE ! 🎉"
M_FINAL_ADDR="📍 L'ADRESSE DE TON SERVEUR (envoie-la à tes amis !) :"
M_FINAL_KNOW="ET MAINTENANT, 3 choses à savoir :"
M_FINAL_1="1️⃣  IL FAUT OUVRIR LES PORTS (une seule fois, 3 minutes, sinon"
M_FINAL_1b="     personne ne peut se connecter) → docs/oci-vcn-config.md"
M_FINAL_2_MOD="2️⃣  Chaque joueur doit installer les MÊMES mods sur SON ordi"
M_FINAL_2_MODb="     avec l'app CurseForge (même modpack, même version)."
M_FINAL_2_VAN="2️⃣  Dans Minecraft : Multijoueur → Ajouter un serveur → colle"
M_FINAL_2_VANb="     l'adresse ci-dessus → Rejoindre !"
M_FINAL_3="3️⃣  Pour devenir le chef en jeu (admin) : rejoins d'abord le serveur"
M_FINAL_3b="       une fois, puis tape : ./utils/console.sh \"op TonPseudo\""
M_FINAL_TOOLS="Boîte à outils : ./utils/backup.sh (sauvegarde) — ./utils/monitor.sh (surveillance)"
M_FINAL_HELP="Un problème ?  : docs/troubleshooting.md"
M_FINAL_GUIDEQ="Ouvrir le guide « ouvrir les ports » dans ton navigateur maintenant ?"
M_FINAL_GUIDEFALL="Lis le fichier docs/oci-vcn-config.md"
M_FINAL_CRAFTYQ="Ouvrir le panel Crafty (interface web de ton serveur) ?"
M_FINAL_CRAFTYFALL="Panel :"

# --- Confirmations de sécurité (destructive) ---
M_DEL_WORD="SUPPRIMER"
M_DEL_TIP="Tapez ${M_DEL_WORD} pour confirmer :"
M_DEL_CANCEL="Annulé."
M_DEL_LAST_BACKUP="Créer une dernière sauvegarde avant suppression ?"

# --- Erreurs ---
M_ERR_OS="OS non supporté :"
M_ERR_OS_HINT="Utilisez Linux, macOS ou Git Bash (Windows)."
M_ERR_TOOL="Outil requis manquant :"
M_ERR_IP="IP invalide :"
M_ERR_TYPE="Type de serveur invalide :"
M_ERR_VER="Version Minecraft invalide :"
M_ERR_RAM="RAM invalide : Go (entre 2 et 8 — quota Always Free 12 Go)"
M_ERR_KEY="Clé SSH introuvable :"
M_ERR_CRAFTY="--crafty doit valoir true ou false"
M_ERR_MOD="Modpack inconnu :"
M_ERR_URL="--pack-url requis pour un modpack (URL http(s) directe valide)"
M_ERR_OPT="Option inconnue :"
M_ERR_LANG="--lang attend 'fr' ou 'en'"

# --- manage.sh : menu principal (usage quotidien) ---
M_MENU_TITLE="GESTION DU SERVEUR MINECRAFT — MENU"
M_MENU_NOCONF="(aucun serveur configuré — lance ./setup.sh d'abord)"
M_MENU_1="Voir l'état (CPU, RAM, joueurs, TPS)"
M_MENU_2="Envoyer une commande de jeu (op, say, time set…)"
M_MENU_3="Sauvegarder le monde"
M_MENU_4="Restaurer une sauvegarde"
M_MENU_5="Mettre à jour (Minecraft / Forge / modpack)"
M_MENU_6="Installer des mods / un modpack (recherche Modrinth intégrée)"
M_MENU_7="Gérer la whitelist (serveur privé)"
M_MENU_8="Ouvrir le panel web Crafty (façon Aternos, dans le navigateur)"
M_MENU_9="Optimisations OCI (sécurité, keepalive, auto-stop, alertes Discord)"
M_MENU_10="Installer / réparer le serveur (relance setup.sh)"
M_MENU_0="Quitter"
M_MENU_CHOICE="Ton choix"
M_MENU_BAD="Choix invalide (0 à 10)."
M_MENU_BACK="Appuie sur Entrée pour revenir au menu…"
M_MENU_ACTERR="L'action s'est terminée avec une erreur (voir au-dessus)."
M_MENU_CMDQ="Commande à envoyer (ex. \"op TonPseudo\") : "
M_MENU_CMDEMPTY="Commande vide — rien envoyé."
M_MENU_WLQ="Action whitelist (add Pseudo / remove Pseudo / list) : "
M_MENU_WLBAD="Format : add Pseudo, remove Pseudo ou list."
M_MENU_REINSTALL="Relance de l'installation (sans danger : elle préserve le monde)."
M_MENU_SETUPERR="setup.sh s'est arrêté avec une erreur (voir au-dessus)."
M_MENU_BYE="À bientôt sur ton serveur ! 🎮"
M_CRAFTY_NOCONF="Lance d'abord ./setup.sh — le panel n'existe pas encore."
M_CRAFTY_OPEN="Ouverture de https://%s:8443 (accepte l'avertissement de certificat)."
M_CRAFTY_FIRST="Première fois ? Identifiants initiaux : ssh %s@%s 'sudo docker logs crafty_controller'"
M_CRAFTY_IMPORT="Puis dans Crafty : menu 9 → option e (auto-import, 30 secondes)."
M_CRAFTY_ADDR="Adresse du panel : https://%s:8443"

# --- manage.sh : sous-menu OCI ---
M_OCI_TITLE="Optimisations OCI (anti-réclamation + sécurité) :"
M_OCI_A="Durcir SSH (PermitRootLogin no, fail2ban, unattended-upgrades)"
M_OCI_B="Activer le keepalive (brûle CPU pour rester au-dessus de 20% p95)"
M_OCI_B_WARN="⚠️  incompatible avec (c) : choisis l'un OU l'autre"
M_OCI_C="Activer l'auto-stop (arrête le serveur après 30 min sans joueur)"
M_OCI_C_WARN="⚠️  incompatible avec (b) : choisis l'un OU l'autre"
M_OCI_D="Configurer une alerte Discord sur échec"
M_OCI_E="Importer le serveur dans Crafty (auto-import API, une fois)"
M_OCI_Q="Retour au menu principal"
M_OCI_CHOICE="Ton choix : "
M_OCI_BAD="Choix invalide."
M_OCI_NOCONF="Lance d'abord ./setup.sh."
M_OCI_KEEP_Q="Installer le keepalive sur %s ?"
M_OCI_KEEP_WARN="Le keepalive simule de l'activité : n'active PAS l'auto-stop (c) en même temps."
M_OCI_KEEP_OK="Keepalive actif (limité à ~1 cœur via CPUQuota)."
M_OCI_SLEEP_Q="Installer l'auto-stop sur %s ?"
M_OCI_SLEEP_WARN="L'auto-stop éteint le serveur vide : n'active PAS le keepalive (b) en même temps."
M_OCI_SLEEP_OK="Auto-stop actif (vérification toutes les 5 min)."
M_OCI_FAIL="Échec — voir le message ci-dessus."
M_OCI_CANCEL="Annulé."
M_OCI_SENDFAIL="Envoi impossible — vérifie la connexion SSH."
M_OCI_HOOK_1="1. Crée un webhook Discord (Salon → Paramètres → Intégrations → Webhooks)."
M_OCI_HOOK_Q="Colle l'URL du webhook (vide = annuler) : "
M_OCI_HOOK_BAD="URL inattendue — elle doit commencer par https://discord.com/api/webhooks/."
M_OCI_HOOK_OK="Alerte Discord câblée (.env en 600, OnFailure actif)."
M_OCI_SEED_INFO="L'auto-import crée le serveur dans Crafty via son API."
M_OCI_SEED_PASS="Il faut d'abord le mot de passe admin Crafty :"
M_OCI_SEED_Q="Colle le mot de passe admin Crafty (vide = annuler) : "
M_OCI_SEED_OK="Serveur importé — ouvre https://%s:8443 et clique Start."
M_OCI_SEED_FAIL="Échec — vérifie le mot de passe et que Crafty tourne."
